# Generated by Django 2.2.5 on 2019-09-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project1.png', upload_to='images'),
        ),
    ]
